package controller;
public enum Screen {
    LOGIN,HOME,BOOKING,MEMBERSHIPS,CHECKOUT,PROFILE,CONTACT_US,
    DASHBOARD, MEMBER_VIEW, MEMBER_EDIT, TRAINER_VIEW, TRAINER_ENTRY, BRANCH_VIEW, EQUIPMENT_VIEW,EQUPIMENT_ENTRY,
    MEMBERSHIP_TYPE_VIEW, MEMBERSHIP_TYPE_ENTRY,BRANCH_ENTRY, PAYMENT_VIEW, PAYMENT_ENTRY,SESSION_VIEW, SESSION_ENTRY,
    BOOKING_VIEW,BOOKING_ENTRY
}
