package controller;
public enum Screen {
    LOGIN,HOME,BOOKING,MEMBERSHIP_VIEW,CHECKOUT,PROFILE,CONTACT_US,
    DASHBOARD, MEMBER_VIEW, MEMBER_ENTRY, TRAINER_VIEW, TRAINER_ENTRY, BRANCH_VIEW, 
    MEMBERSHIP_TYPE_VIEW, MEMBERSHIP_TYPE_ENTRY,BRANCH_ENTRY, PAYMMENTS_VIEW, PAYMENTS_ENTRY,SESSION_VIEW, SESSION_ENTRY
}
