package core;
public enum Screen {
    DASHBOARD, MEMBER_VIEW, MEMBER_ENTRY, TRAINER_VIEW, TRAINER_ENTRY, BRANCH_VIEW, 
    BRANCH_ENTRY, EQUIPMENT_VIEW, EQUIPMENT_ENTRY, PAYMMENTS_VIEW, PAYMENTS_ENTRY,
    SESSION_VIEW, SESSION_ENTRY
}
